config/routes.rb
Rails.application.routes.draw do
  root to: 'emojis#index'

  resources :emojis do
    get :autocomplete_tag_category, :on => :collection
  end
  resources :tags

  get 'click' => 'emojis#click'

end

app/models/emoji.rb
class Emoji < ActiveRecord::Base
  has_many :taggings
  has_many :tags, through: :taggings
  validates :face, uniqueness: true

  accepts_nested_attributes_for :tags

  # Emoji.create! face: ':)', tags_attributes: [ { name: 'asdf' }]

  def increment_copy_count
    self.copy_count += 1
    self.save
  end

  def tag_list
    tags.join(', ')
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect { |s| s.strip.downcase }.uniq
    self.tags = tag_names.collect { |category| Tag.find_or_initialize_by(category: category) }
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :emojis, through: :taggings 
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :emoji
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/emojis_controller.rb
class EmojisController < ApplicationController
  include EmojisHelper

  autocomplete :tag, :category

  def index
    @emojis = Emoji.all.order(copy_count: :desc)
    @emoji = Emoji.new

    respond_to do |format|
      format.html
      format.json
    end
  end

  def click
    @emoji = Emoji.find(params[:unoji])
    @emoji.increment_copy_count
    redirect_to '/'
  end

  def create
    @emojis = Emoji.all.order(copy_count: :desc)
    @emoji = Emoji.new(emoji_params)
    if !@emoji.valid?
      flash.notice = "Emoji '#{@emoji.face}' already exists."
      redirect_to '/'
    else
      @emoji.save
      flash.notice = "Emoji '#{@emoji.face}' created!"
      redirect_to '/'
    end
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all.order(:category)
    @emoji = Emoji.new
  end
  def show
    @tag = Tag.find(params[:id])
    @emoji = Emoji.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emojis_helper.rb
module EmojisHelper

  def emoji_params
    params.require(:emoji).permit(:face, :tag_list)
  end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/emojis/index.html.erb
<div class="container">
  <%= render :partial => 'layouts/form' %>
  <div class="unoji_group">
    <% count = 0 %>
    <div id='popup'>Copied!</div>
    <% @emojis.each do |emoji| %>
      <%= link_to emoji.face, {:controller => "emojis", :action => "click", :unoji => emoji.id }, remote: true, class: "unoji col-md-2 col-sm-3 col-xs-5 face_#{count}", :"data-clipboard-target" => :".face_#{count}" %>
      <% count += 1 %>
    <% end %>
  </div>
</div>

app/views/layouts/_form.html.erb
<div id='create_unoji'>
  <%= form_for @emoji, :html => {:class => 'form-horizontal unoji-form'} do |f| %>
    <p class='form-face form-group'>
      <%= f.label :face, 'Unoji: ', class: 'col-sm-4 control-label' %>
      <%= f.text_field :face, class: 'form-control', required: true, maxlength: 10 %>
    </p>
    <p class='form-tags form-group'>
      <%= f.label :tag_list, 'Categories: ', class: 'col-sm-4 control-label' %>
      <%= f.autocomplete_field :tag_list, autocomplete_tag_category_emojis_path, 'data-delimiter' => ',', :multiple => false, class: 'auto-tags form-control', required: true %>
    </p>
    <p class='form-btn'>
      <%= f.submit "Submit", :class => 'submit_btn' %>
      <button type="button" formonvalidate class="cancel-btn cancel">Cancel</button>
    </p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>unoji</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  <link href='https://fonts.googleapis.com/css?family=Ubuntu:400,500,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet", type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://cdn.jsdelivr.net/clipboard.js/1.5.12/clipboard.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <div class="nav-title"><%= link_to 'UNOJI', '/' %></div>
    <div class="nav-links">
      <div class="nav-link-cat nav-link"><%= link_to 'Categories', tags_path %></div>
      <div class="nav-link-add nav-link"><a class='add-unoji'>Add unoji</a></div>
    </div>
  </nav>
  <% if flash[:notice] -%>
    <p class="flash"><%= flash.notice %></p>
  <% end %>
  <div id='overlay'>
    <%= yield %>
  </div>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-59807851-1', 'auto');
    ga('send', 'pageview');
</script>
</body>
</html>

app/views/tags/index.html.erb
<div class="container">
  <%= render :partial => 'layouts/form' %>
  <div class="tags_group">
    <% @tags.each do |tag| %>
      <%= link_to tag.category, tag_path(tag), class: 'tags' %>
    <% end %>
  </div>
</div>

app/views/tags/show.html.erb
<div class="container">
  <%= render :partial => 'layouts/form' %>
  <div class="unoji_group">
    <span class="category-name"><%= @tag.category %> unojis</span>
    <% count = 0 %>
    <% @tag.emojis.each do |emoji| %>
      <div id='popup'>Copied!</div>
      <%= link_to emoji.face, {:controller => "emojis", :action => "click", :unoji => emoji.id }, remote: true, class: "unoji col-md-2 col-sm-3 col-xs-5 face_#{count}", :"data-clipboard-target" => :".face_#{count}" %>
      <% count += 1 %>
    <% end %>
  </div>
</div>